### ISSUE TITLE
modules/gmail_check.py

### ISSUE THREAD

**Issue by eupone** [dalunacrobate/DaProfiler#1]
Salut salut ,
petits problemes avec ton module "gmail_check.py", je me suis permis de debug un peu le module a part.

le 1er ,
"DeprecationWarning: please use dns.resolver.resolve() instead" à la ligne 12 mais bon c'est plutot simple a comprendre je pense.

le 2eme,
à la ligne 21 , il est impossible d'appeler l'host au qu'elle tu fait reference pour des raisons qui me sont obscures : 
```
Traceback (most recent call last):
  File "c:\Users\rajos\Desktop\fou\socket-module\test\teeey.py", line 31, in <module>
    print(verify("test@gmail.com"))
  File "c:\Users\rajos\Desktop\fou\socket-module\test\teeey.py", line 21, in verify
    server.connect(mxRecord)
  File "C:\Users\rajos\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 336, in connect    
    self.sock = self._get_socket(host, port, self.timeout)
  File "C:\Users\rajos\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 307, in _get_socket
    self.source_address)
  File "C:\Users\rajos\AppData\Local\Programs\Python\Python37\lib\socket.py", line 728, in create_connection
    raise err
  File "C:\Users\rajos\AppData\Local\Programs\Python\Python37\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu
```
(c'est clairement illisible).

du coup je te propose une solution que j'ai trouvé et un peu modifier a ma sauce pour que tu es juste a copier collé
```py
#trouvé sur "https://docs.isitarealemail.com/how-to-validate-email-addresses-in-python"
# modifié (un peu) par eupone
import requests

def verify(mail):
    response = requests.get("https://isitarealemail.com/api/email/validate",params = {'email': mail})

    status = response.json()['status']
    if status == "valid":
        return True
    elif status == "invalid":
        return False
    else:
        return False
```
sur ce bonne soirée et good luck !

**Comment by dalunacrobate** [comment]
> Salut salut ,
> petits problemes avec ton module "gmail_check.py", je me suis permis de debug un peu le module a part.
> 
> le 1er ,
> "DeprecationWarning: please use dns.resolver.resolve() instead" à la ligne 12 mais bon c'est plutot simple a comprendre je pense.
> 
> le 2eme,
> à la ligne 21 , il est impossible d'appeler l'host au qu'elle tu fait reference pour des raisons qui me sont obscures :
> 
> ```
> Traceback (most recent call last):
>   File "c:\Users\rajos\Desktop\fou\socket-module\test\teeey.py", line 31, in <module>
>     print(verify("test@gmail.com"))
>   File "c:\Users\rajos\Desktop\fou\socket-module\test\teeey.py", line 21, in verify
>     server.connect(mxRecord)
>   File "C:\Users\rajos\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 336, in connect    
>     self.sock = self._get_socket(host, port, self.timeout)
>   File "C:\Users\rajos\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 307, in _get_socket
>     self.source_address)
>   File "C:\Users\rajos\AppData\Local\Programs\Python\Python37\lib\socket.py", line 728, in create_connection
>     raise err
>   File "C:\Users\rajos\AppData\Local\Programs\Python\Python37\lib\socket.py", line 716, in create_connection
>     sock.connect(sa)
> TimeoutError: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu
> ```
> 
> (c'est clairement illisible).
> 
> du coup je te propose une solution que j'ai trouvé et un peu modifier a ma sauce pour que tu es juste a copier collé
> 
> ```python
> #trouvé sur "https://docs.isitarealemail.com/how-to-validate-email-addresses-in-python"
> # modifié (un peu) par eupone
> import requests
> 
> def verify(mail):
>     response = requests.get("https://isitarealemail.com/api/email/validate",params = {'email': mail})
> 
>     status = response.json()['status']
>     if status == "valid":
>         return True
>     elif status == "invalid":
>         return False
>     else:
>         return False
> ```
> 
> sur ce bonne soirée et good luck !

Mercii, en cherchant j'avais pas trouvé cette source, elle me permet maintenant de vérifier + de ndd d'adresses mail, avant j'étais limité à Google
