### ISSUE TITLE
Erreur lors du lancement du programme.

### ISSUE THREAD

**Issue by Brieg-Luz** [dalunacrobate/DaProfiler#4]
Lorsque je lance le programme, quelles que soient les options, cela m'affiche :

`Traceback (most recent call last):
  File "profiler.py", line 2, in <module>
    import threading, time, colorama, treelib, random, sys, os, argparse
ModuleNotFoundError: No module named 'treelib'
`
Bonne chance !

**Comment by dalunacrobate** [comment]
Salut @Philibert-Gentil, Regarde si tu as bien installé les requirements : 

`pip install -r requirements.txt`

Si c'est le cas, tu as peut etre installé **les requirements dans une version différente que celle que tu utilises pour exécuter DaProfiler**. Pour régler ça désinstalle tes anciennes versions de python puis tente de re installer les requirements ensuite. Si le problème persiste alors tente de désinstaller toute version de Python pour installer la nouvelle [ici](https://www.python.org/downloads/) .

Si tu as toujours ce problème malheuresement je ne saurais pas t'aider + que ça, si tu tiens à utiliser DaProfiler tu peux toujours installer une légère vm linux et tout faire dessus. Bonne journée !

**Comment by Brieg-Luz** [comment]
Ach sheisse, j'ai trouvé, c'est httpd qui ne veux pas s'installer sur ma machine, mais je suis déjà sur linux, je suis sur ubuntu 20.10 arm64, peut être un problème de version de httpd par rapport a l'architecture.
Merci quand même , bonne vacances !
